### ISSUE TITLE
Exporting with frame interpolation results in ZeroDivisionError exception

### ISSUE THREAD

**Issue by adam-huganir** [heartexlabs/label-studio-tools#40]
This is the same issue seen and described here: https://github.com/heartexlabs/label-studio/issues/3355
This comes up when trying to export with frame interpolation from the UI, though without frame interpolation via the api works fine.

Due to data restrictions I am unable to share much information other than the traceback (sorry), but I hope by adding this to the right repo someone might see the issue and be familiar enough with the code to see the problem.

The traceback hits at [delta = i / (frame_count - 1)](https://github.com/heartexlabs/label-studio-tools/blob/master/label_studio_tools/postprocessing/video.py#L68) and the only reason that could happen from what I can see is if `frame2['frame']  == frame1['frame'] `  or `frameCount == frame1['frame']` when looking at how `frameCount` is defined. I'm not familiar enough with the data schema to offer more insight unfortunately.

If I am able to get the same error with non-controlled data I can post that here, but I suspect I will not be able to.

Thanks

**Comment by makseq** [comment]
@adam-huganir fixed in https://github.com/heartexlabs/label-studio-tools/pull/42, will be delivered in upcoming releases.

**Comment by adam-huganir** [comment]
Awesome, thanks. I'll comment back once it gets released

**Comment by KonstantinKorotaev** [comment]
@adam-huganir 
Please update label-studio-tools to 0.0.2 and check your case one more time

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio-tools/issues/40
https://github.com/heartexlabs/label-studio/issues/3355
